// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        int32     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
}

type Order struct {
	ID        int32       `json:"id"`
	UpdatedAt time.Time   `json:"updated_at"`
	CreatedAt time.Time   `json:"created_at"`
	Status    interface{} `json:"status"`
	UserID    int64       `json:"user_id"`
}

type OrderItem struct {
	ID        int32     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
	Quantity  int32     `json:"quantity"`
	Price     int32     `json:"price"`
	OrderID   int32     `json:"order_id"`
	ProductID int32     `json:"product_id"`
}

type Product struct {
	ID          int32     `json:"id"`
	UpdatedAt   time.Time `json:"updated_at"`
	CreatedAt   time.Time `json:"created_at"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	Price       int32     `json:"price"`
	Images      []string  `json:"images"`
	CategoryID  int32     `json:"category_id"`
}

type Review struct {
	ID        int32     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
	Rating    int32     `json:"rating"`
	Text      string    `json:"text"`
	UserID    int64     `json:"user_id"`
	ProductID int32     `json:"product_id"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
	Userid       int64     `json:"userid"`
}

type User struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
	Phone      string    `json:"phone"`
	Password   string    `json:"password"`
	AvatarPath string    `json:"avatar_path"`
	UpdatedAt  time.Time `json:"updated_at"`
	CreatedAt  time.Time `json:"created_at"`
}
