// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: product_query.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO "product" (
                       "category_id",
                       "name",
                    "slug",
                    "description",
                       "price",
                       "images"
)
VALUES ($1, $2, $3,$4,$5,$6) RETURNING id, updated_at, created_at, name, slug, description, price, images, user_id, category_id
`

type CreateProductParams struct {
	CategoryID  int32    `json:"category_id"`
	Name        string   `json:"name"`
	Slug        string   `json:"slug"`
	Description string   `json:"description"`
	Price       int32    `json:"price"`
	Images      []string `json:"images"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.Images,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Images,
		&i.UserID,
		&i.CategoryID,
	)
	return i, err
}
