// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: profile_query.sql

package db

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, password, avatar_path, updated_at, created_at FROM "user"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.AvatarPath,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
