// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: review_query.sql

package db

import (
	"context"
)

const createReview = `-- name: CreateReview :one
INSERT INTO "review" (
                      "user_id",
                      "product_id",
                     "rating",
                       "text"

)
VALUES ($1, $2,$3,$4) RETURNING id, updated_at, created_at, rating, text, user_id, product_id
`

type CreateReviewParams struct {
	UserID    int64  `json:"user_id"`
	ProductID int32  `json:"product_id"`
	Rating    int32  `json:"rating"`
	Text      string `json:"text"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.ProductID,
		arg.Rating,
		arg.Text,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Rating,
		&i.Text,
		&i.UserID,
		&i.ProductID,
	)
	return i, err
}
